/********************************************************************************************************************************/
/* Created: 12-Jun-2014 13:31:49 by OpenVMS SDL EV2-3      */
/* Source:  12-JUN-2014 13:31:48 MG_ETC:[MMK]MMK_MSG.SDL;10 */
/********************************************************************************************************************************/
/*** MODULE $MMKDEF ***/
/*                                                                          */
/* This SDL File Generated by VAX-11 Message V04-00 on 12-JUN-2014 13:31:48.94 */
/*                                                                          */
#define MMK_FACILITY 3092
/*++                                                                        */
/*                                                                          */
/* DESCRIPTION:                                                             */
/*                                                                          */
/*   THESE ARE THE MESSAGE CODES USED BY THE MMK UTILITY.                   */
/*                                                                          */
/* AUTHOR:   	    M. MADISON                                              */
/*   	    	    COPYRIGHT © 1992-1998, MADGOAT SOFTWARE.                */
/*   	    	    COPYRIGHT © 2014, ENDLESS SOFTWARE SOLUTIONS.           */
/*   	    	    ALL RIGHTS RESERVED.                                    */
/*                                                                          */
/* CREATION DATE: 20-AUG-1992                                               */
/*                                                                          */
/* MODIFICATION HISTORY:                                                    */
/*                                                                          */
/*   20-AUG-1992	V1.0	MADISON	    INITIAL CODING.                 */
/*   29-SEP-1992	V1.1	MADISON	    ADD IDENT, COPYRIGHT, OPENOUT.  */
/*   04-JUN-1993	V1.2	MADISON	    ADD INCLUDE-FILE MESSAGES.      */
/*   17-OCT-1993	V1.2-1	MADISON	    CHANGE IDENT MESSAGE.           */
/*   12-DEC-1993	V1.3	MADISON	    ADD AMBDEPEND.                  */
/*   12-JUL-1994	V1.4	MADISON	    ADD CONDSKIP, ACTNOUPD, CIRCDEP. */
/*   02-DEC-1994	V1.5	MADISON	    ADD ERRLOC.                     */
/*   28-DEC-1994	V1.6	MADISON	    ADD MULACTION.                  */
/*   21-JUN-1995	V1.7	MADISON	    ADD MACFILSYNTAX.               */
/*   22-JUN-1995	V1.7-1	MADISON	    ADD ACTNODEPRULE.               */
/*   06-JUN-1998	V1.8	MADISON	    ADD SETDEF, SETDEFERR.          */
/*   07-SEP-1998	V1.8-1	MAIDSON	    ADD CMDLENERR.                  */
/*   24-OCT-2008 V1.9	SNEDDON	    ADD ELSIFNOIF.                          */
/*   03-FEB-2011 V1.10	SNEDDON	    ADD INSFARGS, TOOMANYARGS.              */
/*   09-FEB-2011 V1.11	SNEDDON	    ADD NYI, BADPARAM.                      */
/*   10-FEB-2011 V1.12	SNEDDON	    ADD INFO, WARN, ERROR                   */
/*   17-MAY-2011 V1.13   SNEDDON	    CHANGE IDENT MESSAGE.           */
/*   03-AUG-2012 V1.14   SNEDDON	    ADD UTLBADMAC.                  */
/*   28-AUG-2012 V1.15   SNEDDON	    ADD UNRFUN. FIXUP ERROR, INFO, WARN. */
/*   03-SEP-2012 V1.15-1 SNEDDON	    CHANGE UTLBADMAC TO REMOVE LINE NUMBER. */
/*   10-JUN-2014 V1.16   SNEDDON	    ADD NOTINSUFFLST, ALRINSUFFLST, NOSUFFLST. */
/*   12-JUN-2014 V1.16-1 SNEDDON     FIXED FAO STRING DIRECTIVES FOR ABOVE. */
/*--                                                                        */
#define MMK__NOOPNDSC 202670092
#define MMK__PARSERR 202670100
#define MMK__PRSTBLERR 202670108
#define MMK__NOALLOC 202670116
#define MMK__NOTARGETS 202670124
#define MMK__NOSUCHTRG 202670132
#define MMK__ERRUPD 202670140
#define MMK__SRCERR 202670148
#define MMK__NOACTION 202670156
#define MMK__OPENOUT 202670164
#define MMK__CANTUPD 202670172
#define MMK__SDCMIX 202670180
#define MMK__MULACTION 202670188
#define MMK__MACFILSYNTAX 202670196
#define MMK__ACTNODEPRULE 202670204
#define MMK__NYI 202670212
#define MMK__BADPARAM 202670220
#define MMK__ERROR 202670228
#define MMK__ELSENOIF 202670234
#define MMK__ENDIFNOIF 202670242
#define MMK__ELSIFNOIF 202670250
#define MMK__ELSIFAFTELSE 202670258
#define MMK__NOOPNRUL 202670264
#define MMK__NOOPNINCL 202670272
#define MMK__AMBDEPEND 202670280
#define MMK__CONDSKIP 202670288
#define MMK__CIRCDEP 202670296
#define MMK__CONNEXION 202670304
#define MMK__INSFARGS 202670312
#define MMK__TOOMANYARGS 202670320
#define MMK__WARN 202670328
#define MMK__OPENDESC 202670339
#define MMK__OPENRULE 202670347
#define MMK__OPENINCL 202670355
#define MMK__CHECKUPD 202670363
#define MMK__TRGLKUF 202670371
#define MMK__TRGNUPD 202670379
#define MMK__TRGRDT 202670387
#define MMK__SRCRDT 202670395
#define MMK__PERFUPD 202670403
#define MMK__IDENT 202670411
#define MMK__COPYRIGHT 202670419
#define MMK__ACTNOUPD 202670427
#define MMK__ERRLOC 202670435
#define MMK__NEEDSUPD 202670443
#define MMK__TRGCURRENT 202670451
#define MMK__INFO 202670459
#define MMK__NOUPDATE 202670465
#define MMK__SETDEF 202670475
#define MMK__SETDEFERR 202670482
#define MMK__CMDLENERR 202670490
#define MMK__UTLBADMAC 202670496
#define MMK__UNRFUN 202670504
#define MMK__ALRINSUFFLST 202670515
#define MMK__NOSUFFLST 202670523
#define MMK__NOTINSUFFLST 202670531
 
